# Generated by Django 5.0.3 on 2024-04-24 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_liked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thepost', to='theapp.thepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
